# This file is automatically generated by data-raw/create_adams_data.R.
# For updating it please edit inst/extdata/adams-specs.xlsx and rerun create_adams_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#'
#' @name adpc
#' @title Pharmacokinetic Concentrations
#' @docType data
#' @format A data frame with 127 columns:
#'   \describe{
#'     \item{ STUDYID }{Study Identifier}
#'     \item{ USUBJID }{Unique Subject Identifier}
#'     \item{ SUBJID }{Subject Identifier for the Study}
#'     \item{ SITEID }{Study Site Identifier}
#'     \item{ COUNTRY }{Country}
#'     \item{ RFSTDTC }{Subject Reference Start Date/Time}
#'     \item{ RFENDTC }{Subject Reference End Date/Time}
#'     \item{ RFXSTDTC }{Date/Time of First Study Treatment}
#'     \item{ RFXENDTC }{Date/Time of Last Study Treatment}
#'     \item{ RFPENDTC }{Date/Time of End of Participation}
#'     \item{ SCRFDT }{Screen Failure Date}
#'     \item{ FRVDT }{Final Retrieval Visit Date}
#'     \item{ DTHDTC }{Date/Time of Death}
#'     \item{ DTHADY }{Relative Day of Death}
#'     \item{ DTHFL }{Subject Death Flag}
#'     \item{ LDDTHELD }{Elapsed Days from Last Dose to Death}
#'     \item{ LDDTHGR1 }{Last Dose to Death - Days Elapsed Grp 1}
#'     \item{ DTH30FL }{Under 30  Group}
#'     \item{ DTHA30FL }{Over 30  Group}
#'     \item{ DTHDOM }{Domain for Date of Death Collection}
#'     \item{ DTHB30FL }{Over 30 plus 30 days Group}
#'     \item{ ASEQ }{Analysis Sequence Number}
#'     \item{ REGION1 }{Geographic Region 1}
#'     \item{ DMDTC }{Date/Time of Collection}
#'     \item{ DMDY }{Study Day of Collection}
#'     \item{ AGE }{Age}
#'     \item{ AGEU }{Age Units}
#'     \item{ AGEGR1 }{Pooled Age Group 1}
#'     \item{ SEX }{Sex}
#'     \item{ RACE }{Race}
#'     \item{ RACEGR1 }{Pooled Race Group 1}
#'     \item{ ETHNIC }{Ethnicity}
#'     \item{ SAFFL }{Safety Population Flag}
#'     \item{ ARM }{Description of Planned Arm}
#'     \item{ ARMCD }{Planned Arm Code}
#'     \item{ ACTARM }{Description of Actual Arm}
#'     \item{ ACTARMCD }{Actual Arm Code}
#'     \item{ TRT01P }{Planned Treatment for Period 01}
#'     \item{ TRT01A }{Actual Treatment for Period 01}
#'     \item{ TRTSDT }{Date of First Exposure to Treatment}
#'     \item{ TRTSDTM }{Datetime of First Exposure to Treatment}
#'     \item{ TRTSTMF }{Time of First Exposure Imput. Flag}
#'     \item{ TRTEDT }{Date of Last Exposure to Treatment}
#'     \item{ TRTEDTM }{Datetime of Last Exposure to Treatment}
#'     \item{ TRTETMF }{Time of Last Exposure Imput. Flag}
#'     \item{ EOSSTT }{End of Study Status}
#'     \item{ EOSDT }{End of Study Date}
#'     \item{ RFICDTC }{Date/Time of Informed Consent}
#'     \item{ RANDDT }{Date of Randomization}
#'     \item{ LSTALVDT }{Date Last Known Alive}
#'     \item{ TRTDURD }{Total Treatment Duration (Days)}
#'     \item{ DTHDT }{Date of Death}
#'     \item{ DTHDTF }{Date of Death Imputation Flag}
#'     \item{ DTHCAUS }{Cause of Death}
#'     \item{ DTHCGR1 }{Cause of Death Reason 1}
#'     \item{ DOSEP }{Planned Treatment Dose}
#'     \item{ DOSEA }{Actual Treatment Dose}
#'     \item{ DOSEU }{Treatment Dose Units}
#'     \item{ ADT }{Analysis Date}
#'     \item{ ATM }{Analysis Time}
#'     \item{ ADTM }{Analysis Datetime}
#'     \item{ ADY }{Analysis Relative Day}
#'     \item{ ATMF }{Analysis Time Imputation Flag}
#'     \item{ ASTDT }{Analysis Start Date}
#'     \item{ ASTTM }{Analysis Start Time}
#'     \item{ ASTDTM }{Analysis Start Datetime}
#'     \item{ AENDT }{Analysis End Date}
#'     \item{ AENTM }{Analysis End Time}
#'     \item{ AENDTM }{Analysis End Datetime}
#'     \item{ AVISIT }{Analysis Visit}
#'     \item{ AVISITN }{Analysis Visit (N)}
#'     \item{ ATPT }{Analysis Timepoint}
#'     \item{ ATPTN }{Analysis Timepoint (N)}
#'     \item{ ATPTREF }{Analysis Timepoint Reference}
#'     \item{ PARAM }{Parameter}
#'     \item{ PARAMCD }{Parameter Code}
#'     \item{ PARAMN }{Parameter (N)}
#'     \item{ PARCAT1 }{Parameter Category 1}
#'     \item{ AVAL }{Analysis Value}
#'     \item{ AVALU }{Analysis Value Unit}
#'     \item{ AVALCAT1 }{Analysis Value Category 1}
#'     \item{ BASE }{Baseline Value}
#'     \item{ BASETYPE }{Baseline Type}
#'     \item{ CHG }{Change from Baseline}
#'     \item{ DTYPE }{Derivation Type}
#'     \item{ ABLFL }{Baseline Record Flag}
#'     \item{ ANL01FL }{Analysis Flag 01}
#'     \item{ ANL02FL }{Analysis Flag 02}
#'     \item{ SRCDOM }{Source Data}
#'     \item{ SRCVAR }{Source Variable}
#'     \item{ SRCSEQ }{Source Sequence Number}
#'     \item{ NFRLT }{Nom. Rel. Time from Analyte First Dose}
#'     \item{ PCTESTCD }{Pharmacokinetic Test Short Name}
#'     \item{ PCTEST }{Pharmacokinetic Test Name}
#'     \item{ PCORRES }{Result or Finding in Original Units}
#'     \item{ PCORRESU }{Original Units}
#'     \item{ PCSTRESC }{Character Result/Finding in Std Format}
#'     \item{ PCSTRESN }{Numeric Result/Finding in Standard Units}
#'     \item{ PCSTRESU }{Standard Units}
#'     \item{ PCNAM }{Vendor Name}
#'     \item{ PCSPEC }{Specimen Material Type}
#'     \item{ PCLLOQ }{Lower Limit of Quantitation}
#'     \item{ VISIT }{Visit Name}
#'     \item{ VISITNUM }{Visit Number}
#'     \item{ PCDTC }{Date/Time of Specimen Collection}
#'     \item{ PCDY }{Actual Study Day of Specimen Collection}
#'     \item{ PCTPT }{Planned Time Point Name}
#'     \item{ PCTPTNUM }{Planned Time Point Number}
#'     \item{ FANLDTM }{First Datetime of Dose for Analyte}
#'     \item{ AFRLT }{Act. Rel. Time from Analyte First Dose}
#'     \item{ ARRLT }{Actual Rel. Time from Ref. Dose}
#'     \item{ PCRFTDTM }{Reference Datetime of Dose for Analyte}
#'     \item{ FANLDT }{First Date of Dose for Analyte}
#'     \item{ FANLTM }{First Time of Dose for Analyte}
#'     \item{ PCRFTDT }{Reference Date of Dose for Analyte}
#'     \item{ PCRFTTM }{Reference Time of Dose for Analyte}
#'     \item{ NRRLT }{Nominal Rel. Time from Ref. Dose}
#'     \item{ FRLTU }{Rel. Time from First Dose Unit}
#'     \item{ RRLTU }{Rel. Time from Ref. Dose Unit}
#'     \item{ ALLOQ }{Analysis Lower Limit of Quantitation}
#'     \item{ MRRLT }{Modified Rel. Time from Ref. Dose}
#'     \item{ HTBL }{Numeric Result/Finding in Standard Units}
#'     \item{ HTBLU }{Standard Units}
#'     \item{ WTBL }{Numeric Result/Finding in Standard Units}
#'     \item{ WTBLU }{Standard Units}
#'     \item{ BMIBL }{Baseline Body Mass Index (kg/m2)}
#'     \item{ BMIBLU }{BMI at Baseline (Unit)}
#'   }
#' @details Contains a set of 2 unique Parameter Codes and Parameters: \tabular{ll}{
#'   \strong{PARAMCD} \tab \strong{PARAM} \cr
#'   DOSE \tab Xanomeline Patch Dose                      \cr
#'   XAN  \tab Pharmacokinetic concentration of Xanomeline
#' }

#'
#' @source Generated from admiral package (template ad_adpc.R).
#' @references None
#'
#' @examples
#' data("adpc")
"adpc"
