# This file is automatically generated by data-raw/create_adams_data.R.
# For updating it please edit inst/extdata/adams-specs.xlsx and rerun create_adams_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#'
#' @name adppk
#' @title Population Pharmacokinetic
#' @keywords dataset generic
#' @docType data
#' @format A data frame with 61 columns:
#'   \describe{
#'     \item{ PROJID }{Project Identifier}
#'     \item{ PROJIDN }{Project Identifier (N)}
#'     \item{ STUDYID }{Study Identifier}
#'     \item{ STUDYIDN }{Study Identifier (N)}
#'     \item{ USUBJID }{Unique Subject Identifier}
#'     \item{ USUBJIDN }{Unique Subject Identifier (N)}
#'     \item{ SUBJID }{Subject Identifier for the Study}
#'     \item{ SUBJIDN }{Subject Identifier for the Study (N)}
#'     \item{ SITEID }{Study Site Identifier}
#'     \item{ SITEIDN }{Study Site Identifier (N)}
#'     \item{ RECSEQ }{Record Sequence}
#'     \item{ AFRLT }{Act. Rel. Time from Analyte First Dose}
#'     \item{ APRLT }{Actual Rel Time from Previous Dose}
#'     \item{ NFRLT }{Nom. Rel. Time from Analyte First Dose}
#'     \item{ NPRLT }{Nominal Rel Time from Previous Dose}
#'     \item{ EVID }{Event ID}
#'     \item{ CMT }{Compartment}
#'     \item{ DV }{Dependent Variable Result}
#'     \item{ PARAMCD }{Parameter Code}
#'     \item{ PARAM }{Parameter}
#'     \item{ PARAMN }{Parameter (N)}
#'     \item{ ASEQ }{Analysis Sequence Number}
#'     \item{ AVAL }{Analysis Value}
#'     \item{ AVALU }{Analysis Value Unit}
#'     \item{ MDV }{Missing Dependent Variable Result}
#'     \item{ ALLOQ }{Analysis Lower Limit of Quantitation}
#'     \item{ BLQFL }{Below Lower Limit of Quant Flag}
#'     \item{ BLQFN }{Below Lower Limit of Quant Flag (N)}
#'     \item{ AMT }{Actual Amount of Dose Received (unit)}
#'     \item{ DOSEA }{Actual Treatment Dose}
#'     \item{ II }{Dosing Interval (unit)}
#'     \item{ SS }{Steady State}
#'     \item{ FORM }{Drug Formulation}
#'     \item{ FORMN }{Drug Formulation (N)}
#'     \item{ ROUTE }{Route of Administration}
#'     \item{ ROUTEN }{Route of Administration (N)}
#'     \item{ COHORT }{Cohort Subject Enrolled Into}
#'     \item{ COHORTC }{Description of Planned Arm}
#'     \item{ UDTC }{Date/Time}
#'     \item{ WTBL }{Numeric Result/Finding in Standard Units}
#'     \item{ HTBL }{Numeric Result/Finding in Standard Units}
#'     \item{ BMIBL }{Baseline Body Mass Index (kg/m2)}
#'     \item{ BSABL }{Numeric Result/Finding in Standard Units}
#'     \item{ AGE }{Age}
#'     \item{ SEX }{Sex}
#'     \item{ SEXN }{Sex (N)}
#'     \item{ RACE }{Race}
#'     \item{ RACEN }{Race (N)}
#'     \item{ ETHNIC }{Ethnicity}
#'     \item{ ETHNICN }{Ethnicity (N)}
#'     \item{ COUNTRY }{Country}
#'     \item{ COUNTRYL }{Country Name}
#'     \item{ COUNTRYN }{Country (N)}
#'     \item{ CREATBL }{Numeric Result/Finding in Standard Units}
#'     \item{ CRCLBL }{Baseline Creatinine Clearance}
#'     \item{ EGFRBL }{Age}
#'     \item{ TBILBL }{Numeric Result/Finding in Standard Units}
#'     \item{ ASTBL }{Numeric Result/Finding in Standard Units}
#'     \item{ ALTBL }{Numeric Result/Finding in Standard Units}
#'     \item{ DOSEP }{Planned Treatment Dose}
#'     \item{ DVL }{Log DV}
#'   }
#' @details Contains a set of 2 unique Parameter Codes and Parameters: \tabular{ll}{
#'   \strong{PARAMCD} \tab \strong{PARAM} \cr
#'   DOSE \tab Xanomeline Patch Dose                      \cr
#'   XAN  \tab Pharmacokinetic concentration of Xanomeline
#' }

#'
#' @source Generated from admiral package (template ad_adppk.R).
#' @references None
#'
#' @examples
#' data("adppk")
"adppk"
